title: Hornazos por el mundo
slogan: Ness & Bicco ðŸ‘¨â€ðŸ³ðŸ‘©â€ðŸ³ 
email: victorsantoja@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
twitter_username: 
github_username: 

# Build settings
#Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

#without other theme
#theme: minima

# Assets
exclude: [CONTRIBUTING.md', 'Gemfile', 'Gemfile.lock', 'GLOSSARY', 'Procfile', 'Rakefile', 'README.md', 'vendor', 'LICENSE']
assets:
  compress:
    css: sass
    js:  uglifier
  digest: true
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts

#Plugin
plugins:
  - jekyll-feed
  - jekyll-octicons

