title: Hornazos por el mundo
slogan: Ness & Bicco ðŸ‘¨â€ðŸ³ðŸ‘©â€ðŸ³ 
email: victorsantoja@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "127.0.0.0:4000"
twitter_username: 
github_username: 

# Build settings
#Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

#without other theme
#theme: minima

#Plugin
plugins:
  - jekyll-feed
  - jekyll-octicons

